In [1]:
import pandas as pd 

df = pd.read_csv('touristic_homes_HUT.csv')

df.head()

,district_code,longitude,staircase,number_type,building_entrance,street_type,street_number_start,street_number_end,district_name,neighbourhood_name,...,door,letter2,number_of_places,expedient_number,letter1,latitude,block,street_name,neighbourhood_code,id
0,1,"2,17017206787341",NaN,1,NaN,Carrer,19,NaN,CIUTAT VELLA,el Raval,...,1,NaN,3.0,01-2009-0354,NaN,"41,3784454355655",NaN,SANT JOSEP ORIOL,1.0,1
1,1,"2,18200417667745",NaN,2,NaN,Carrer,22,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",...,NaN,NaN,3.0,01-2011-0123,NaN,"41,3828840594187",NaN,AGULLERS,4.0,2
2,1,"2,17308601359367",NaN,2,NaN,Carrer,8,NaN,CIUTAT VELLA,el Barri Gòtic,...,2,NaN,3.0,01-2011-0137,NaN,"41,3822240718426",NaN,ROCA,2.0,3
3,1,"2,18200417667745",NaN,2,NaN,Carrer,22,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",...,NaN,NaN,3.0,01-2011-0152,NaN,"41,3828840594187",NaN,AGULLERS,4.0,4
4,1,"2,18330533470055",NaN,1,NaN,Plaça,9,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",...,2,NaN,9.0,01-2011-0157,B,"41,3836849458057",NaN,OLLES,4.0,5

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
df.head()

,district_code,longitude,staircase,number_type,building_entrance,street_type,street_number_start,street_number_end,district_name,neighbourhood_name,generalitat_register_number,floor,door,letter2,number_of_places,expedient_number,letter1,latitude,block,street_name,neighbourhood_code,id
0,1,"2,17017206787341",NaN,1,NaN,Carrer,19,NaN,CIUTAT VELLA,el Raval,HUTB-002222,01,1,NaN,3.0,01-2009-0354,NaN,"41,3784454355655",NaN,SANT JOSEP ORIOL,1.0,1
1,1,"2,18200417667745",NaN,2,NaN,Carrer,22,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",HUTB-003654,1,NaN,NaN,3.0,01-2011-0123,NaN,"41,3828840594187",NaN,AGULLERS,4.0,2
2,1,"2,17308601359367",NaN,2,NaN,Carrer,8,NaN,CIUTAT VELLA,el Barri Gòtic,HUTB-001678,01,2,NaN,3.0,01-2011-0137,NaN,"41,3822240718426",NaN,ROCA,2.0,3
3,1,"2,18200417667745",NaN,2,NaN,Carrer,22,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",HUTB-003650,2,NaN,NaN,3.0,01-2011-0152,NaN,"41,3828840594187",NaN,AGULLERS,4.0,4
4,1,"2,18330533470055",NaN,1,NaN,Plaça,9,NaN,CIUTAT VELLA,"Sant Pere, Santa Caterina i la Ribera",HUTB-002534,01,2,NaN,9.0,01-2011-0157,B,"41,3836849458057",NaN,OLLES,4.0,5